# Generated by Django 4.1.3 on 2022-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_refurbished_refurbished'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='percentile',
            field=models.IntegerField(default=10),
        ),
    ]
