# Generated by Django 4.1.3 on 2022-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_discount_percentile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expireson',
            field=models.DateField(),
        ),
    ]
