# Generated by Django 4.1.3 on 2022-12-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_discount_is_active_delete_refurbished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
    ]
