# Generated by Django 4.1.3 on 2022-12-15 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('refurbished_count', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
