# Generated by Django 4.1.3 on 2022-12-15 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_count_refurbished_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='refurbished_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
