# Generated by Django 4.1.3 on 2023-01-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_count_refurbished_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(related_name='discount', to='product.product'),
        ),
    ]
