# Generated by Django 4.1.3 on 2022-12-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
