# Generated by Django 4.1.3 on 2022-12-16 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_reciept_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
