# Generated by Django 4.1.3 on 2022-12-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date_time',
            new_name='date',
        ),
    ]
