# Generated by Django 4.1.3 on 2022-12-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_date_time_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='isdelivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
