# Generated by Django 4.1.3 on 2022-12-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_reciept_isdelivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='isdelivered',
        ),
    ]
