# Generated by Django 4.1.3 on 2022-12-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_reciept_isdelivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='isdelieved',
            field=models.CharField(choices=[('0', 'Order Placed'), ('1', 'Out For Delievery'), ('2', 'Out For Delivery'), ('3', 'Delivered')], default='0', max_length=225),
        ),
    ]
