# Generated by Django 4.1.3 on 2022-12-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_reciept_isdelieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciept',
            old_name='isdelieved',
            new_name='status',
        ),
    ]
