# Generated by Django 4.1.3 on 2022-12-01 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_discount_is_active_delete_refurbished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Payment Processing'), ('1', 'Order Placed'), ('2', 'Out For Delivery'), ('3', 'Delivered')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=10)),
                ('discount', models.ManyToManyField(to='product.discount')),
                ('products', models.ManyToManyField(to='product.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
