# Generated by Django 4.1.3 on 2022-12-03 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_discount_is_active_delete_refurbished'),
        ('order', '0002_alter_order_user_kart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product.product'),
        ),
        migrations.AlterField(
            model_name='kart',
            name='total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
