# Generated by Django 4.1.3 on 2022-12-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_discount_is_active_delete_refurbished'),
        ('order', '0003_alter_kart_products_alter_kart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kart',
            name='products',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
