# Generated by Django 4.1.3 on 2022-12-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_kart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
